### ISSUE TITLE
Gossamer `t` string interpolator doesn't seem work

### ISSUE THREAD

**Issue by sideeffffect** [propensive/gossamer#18]
```scala
import nettlesome.*
import gossamer.*
import contingency.*
import errorHandlers.throwUnsafely

println("hello")
println(t"user-@example.org")
//println(EmailAddress.parse(t"user-@example.org"))
```
Scala version being used is `3.5.0-RC1`

# 1) Scastie
On scastie, it doesn't produce any output
https://scastie.scala-lang.org/bRgE1hMhTsysAgTxj8A0vA

# 2) local sbt project
On local sbt project, it produces this error:
```
[error] -- Error: /Users/propensive/work/gossamer/src/core/t.scala:29:57 ---------------
[error] undefined: gossamer.Interpolation.T.expand # -1: TermRef(TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class <root>)),object gossamer),Interpolation),object T),expand) at typer
```

**Comment by propensive** [comment]
I wonder if I might have made an error with publishing the Maven artifacts... I'll investigate.

**Comment by propensive** [comment]
This was more broken than I thought: I had published Gossamer with a set of dependencies from a different project.

The latest published versions should work. For your example, you can depend on `dev.soundness:nettlesome-core:0.2.0` and all the other dependencies are pulled in, though you might need to update from Scala 3.5.0-RC1 to RC4.

I'll get to work on updating the documentation so that the latest versions are shown everywhere. (Currently, they're not, and it's a mess.)
